import { PlanProps } from "../components/PlanComponent";

export const planData: PlanProps[] = [
  {
    src: "/.png",
    title: "Mini",
    description:
      "Mini plan with access to 10 oot's Aha Telugu, ETV Win, 300 plus live tv channels and 7 others.",
    pricing: [
      { duration: "1m", ourPrice: 70, originalPrice: 14.99 },
      { duration: "3m", ourPrice: 180, originalPrice: 39.99 },
      { duration: "6m", ourPrice: 320, originalPrice: 74.99 },
      { duration: "1y", ourPrice: 600, originalPrice: 149.99 },
    ],
    ottCodes: [
      "ahaTelugu",
      "etvWin",
      "bhaktiFlix",
      "fancode",
      "playFlix",
      "distroTv",
      "powerKids",
      "omTv",
      "iTap",
      "shemarooTv",
      "liveTv",
    ], // Array of OTT codes for this plan
  },
  {
    src: "/plan2_image.png",
    title: "Silver",
    description:
      "Starter Add free ott package with 15 favorite ott's Sun Nxt, Aha Telugu, Sony Liv, Etv Win, 300+ live channels and others",
    pricing: [
      { duration: "1m", ourPrice: 150, originalPrice: 24.99 },
      { duration: "3m", ourPrice: 420, originalPrice: 59.99 },
      { duration: "6m", ourPrice: 800, originalPrice: 109.99 },
      { duration: "1y", ourPrice: 1500, originalPrice: 199.99 },
    ],
    ottCodes: [
      "sunNxt",
      "ahaTelugu",
      "etvWin",
      "sonyLiv",
      "ulluTv",
      "distroTv",
      "dollywoodPlay",
      "shemarooTv",
      "fancode",
      "iTap",
      "omTv",
      "powerKids",
      "primeFilx",
      "runnTv",
      "altBalaji",
      "liveTv",
    ], // Array of OTT codes for this plan
  },
  {
    src: "/plan3_image.png",
    title: "Gold",
    description:
      "Mid budget plan with 20 ott's to fit all kinds of punch into one package to satisify everyone.",
    pricing: [
      { duration: "1m", ourPrice: 200, originalPrice: 24.99 },
      { duration: "3m", ourPrice: 560, originalPrice: 59.99 },
      { duration: "6m", ourPrice: 1150, originalPrice: 109.99 },
      { duration: "1y", ourPrice: 1800, originalPrice: 199.99 },
    ],
    ottCodes: [
      "zee5",
      "sunNxt",
      "ahaTelugu",
      "etvWin",
      "ulluTv",
      "distroTv",
      "dollywoodPlay",
      "shemarooTv",
      "fancode",
      "iTap",
      "omTv",
      "powerKids",
      "primeFilx",
      "runnTv",
      "altBalaji",
      "rajTv",
      "aaoNxt",
      "vrOtt",
      "kancchaLanka",
      "stage",
      "liveTv",
    ], // Array of OTT codes for this plan
  },
  {
    src: "/plan4_image.png",
    title: "Diamond",
    description:
      "Enjoy the 25 ott's that fit for all interest and everyday use along with great amount of live channels.",
    pricing: [
      { duration: "1m", ourPrice: 230, originalPrice: 24.99 },
      { duration: "3m", ourPrice: 670, originalPrice: 59.99 },
      { duration: "6m", ourPrice: 1300, originalPrice: 109.99 },
      { duration: "1y", ourPrice: 2000, originalPrice: 199.99 },
    ],
    ottCodes: [
      "zee5",
      "sunNxt",
      "ahaTelugu",
      "sonyLiv",
      "etvWin",
      "dangalPlay",
      "altBalaji",
      "distroTv",
      "dollywoodPlay",
      "cinemaWorld",
      "runnTv",
      "bhaktiFlix",
      "nammaFlix",
      "omTv",
      "playFlix",
      "powerKids",
      "rajTv",
      "primeFilx",
      "iStream",
      "aaoNxt",
      "iTap",
      "chaupal",
      "vrOtt",
      "shortFundly",
      "shemarooTv",
      "liveTv",
    ], // Array of OTT codes for this plan
  },
  {
    src: "/plan5_image.png",
    title: "Platinum",
    description:
      "Premium plan with 37 ott's to accomodate everyones needs adn ultimate entertainment pack.",
    pricing: [
      { duration: "1m", ourPrice: 270, originalPrice: 24.99 },
      { duration: "3m", ourPrice: 780, originalPrice: 59.99 },
      { duration: "6m", ourPrice: 1500, originalPrice: 109.99 },
      { duration: "1y", ourPrice: 2400, originalPrice: 199.99 },
    ],
    ottCodes: [
      "zee5",
      "sunNxt",
      "ahaTelugu",
      "sonyLiv",
      "lionsgatePlay",
      "fancode",
      "etvWin",
      "ulluTv",
      "dangalPlay",
      "altBalaji",
      "ultraJhakaas",
      "distroTv",
      "dollywoodPlay",
      "cinemaWorld",
      "ptcPlay",
      "runnTv",
      "bhaktiFlix",
      "manoramaMax",
      "pragPlay",
      "omTv",
      "docuBay",
      "stage",
      "playFlix",
      "powerKids",
      "rajTv",
      "primeFilx",
      "iStream",
      "aaoNxt",
      "iTap",
      "chaupal",
      "vrOtt",
      "shortFundly",
      "shortsTv",
      "reelDrama",
      "sanskarTv",
      "ahaTamil",
      "shemarooTv",
      "liveTv",
    ], // Array of OTT codes for this plan
  },
  {
    src: "/plan6_image.png",
    title: "Disney+ Offers",
    description:
      "Get Hotstar Super plan for : Ruppes 250 for 3 months And Ruppes 500 for 6 months And Ruppes 850 for 1 year",
    pricing: [],
    ottCodes: ["hotstar"], // Array of OTT codes for this plan
  },
  {
    src: "/plan7_image.png",
    title: "Prime Offers",
    description:
      "Signup for our team to contact you abot exciting deals on Amazon Prime Video pricing.",
    pricing: [],
    ottCodes: ["primeVideo"], // Array of OTT codes for this plan
  },
  // Add more plan objects as needed
];
