import { PlanProps } from "../components/PlanComponent";

export const planData: PlanProps[] = [
  {
    src: "/.png",
    title: "Mini",
    description:
      "Standard HD plan with access to SonyLIV, ETV Win, Hotstar, ZEE5, Amazon Prime Video, and Netflix.",
    pricing: [
      { duration: "1m", ourPrice: 70, originalPrice: 14.99 },
      { duration: "3m", ourPrice: 180, originalPrice: 39.99 },
      { duration: "6m", ourPrice: 320, originalPrice: 74.99 },
      { duration: "1y", ourPrice: 600, originalPrice: 149.99 },
    ],
    ottCodes: [
      "ahaTelugu",
      "etvWin",
      "bhaktiFlix",
      "playFlix",
      "distroTv",
      "powerKids",
      "omTv",
      "iTap",
      "shemarooTv",
      "liveTv",
    ], // Array of OTT codes for this plan
  },
  {
    src: "/plan2_image.png",
    title: "Silver",
    description:
      "Premium 4K plan with access to SonyLIV, Hotstar, Amazon Prime Video, and Netflix.",
    pricing: [
      { duration: "1m", ourPrice: 150, originalPrice: 24.99 },
      { duration: "3m", ourPrice: 420, originalPrice: 59.99 },
      { duration: "6m", ourPrice: 800, originalPrice: 109.99 },
      { duration: "1y", ourPrice: 1500, originalPrice: 199.99 },
    ],
    ottCodes: [
      "sunNxt",
      "ahaTelugu",
      "etvWin",
      "sonyLiv",
      "ulluTv",
      "distroTv",
      "dollywoodPlay",
      "shemarooTv",
      "fancode",
      "iTap",
      "omTv",
      "powerKids",
      "primeFilx",
      "runnTv",
      "altBalaji",
      "liveTv",
    ], // Array of OTT codes for this plan
  },
  {
    src: "/plan3_image.png",
    title: "Gold",
    description:
      "Premium 4K plan with access to SonyLIV, Hotstar, Amazon Prime Video, and Netflix.",
    pricing: [
      { duration: "1m", ourPrice: 200, originalPrice: 24.99 },
      { duration: "3m", ourPrice: 560, originalPrice: 59.99 },
      { duration: "6m", ourPrice: 1050, originalPrice: 109.99 },
      { duration: "1y", ourPrice: 2000, originalPrice: 199.99 },
    ],
    ottCodes: [
      "zee5",
      "sunNxt",
      "ahaTelugu",
      "etvWin",
      "ulluTv",
      "distroTv",
      "dollywoodPlay",
      "shemarooTv",
      "fancode",
      "iTap",
      "omTv",
      "powerKids",
      "primeFilx",
      "runnTv",
      "altBalaji",
      "rajTv",
      "aaoNxt",
      "vrOtt",
      "kancchaLanka",
      "stage",
      "liveTv",
    ], // Array of OTT codes for this plan
  },
  {
    src: "/plan4_image.png",
    title: "Diamond",
    description:
      "Premium 4K plan with access to SonyLIV, Hotstar, Amazon Prime Video, and Netflix.",
    pricing: [
      { duration: "1m", ourPrice: 200, originalPrice: 24.99 },
      { duration: "3m", ourPrice: 560, originalPrice: 59.99 },
      { duration: "6m", ourPrice: 1050, originalPrice: 109.99 },
      { duration: "1y", ourPrice: 2000, originalPrice: 199.99 },
    ],
    ottCodes: [
      "zee5",
      "sunNxt",
      "ahaTelugu",
      "sonyLiv",
      "etvWin",
      "dangalPlay",
      "altBalaji",
      "distroTv",
      "dollywoodPlay",
      "cinemaWorld",
      "runnTv",
      "bhaktiFlix",
      "nammaFlix",
      "omTv",
      "playFlix",
      "powerKids",
      "rajTv",
      "primeFilx",
      "iStream",
      "aaoNxt",
      "iTap",
      "chaupal",
      "vrOtt",
      "shortFundly",
      "shemarooTv",
      "liveTv",
    ], // Array of OTT codes for this plan
  },
  {
    src: "/plan5_image.png",
    title: "Platinum",
    description:
      "Premium 4K plan with access to SonyLIV, Hotstar, Amazon Prime Video, and Netflix.",
    pricing: [
      { duration: "1m", ourPrice: 260, originalPrice: 24.99 },
      { duration: "3m", ourPrice: 750, originalPrice: 59.99 },
      { duration: "6m", ourPrice: 1400, originalPrice: 109.99 },
      { duration: "1y", ourPrice: 2600, originalPrice: 199.99 },
    ],
    ottCodes: [
      "zee5",
      "sunNxt",
      "ahaTelugu",
      "sonyLiv",
      "lionsgatePlay",
      "fancode",
      "etvWin",
      "ulluTv",
      "dangalPlay",
      "altBalaji",
      "ultraJhakaas",
      "distroTv",
      "dollywoodPlay",
      "cinemaWorld",
      "ptcPlay",
      "runnTv",
      "bhaktiFlix",
      "nammaFlix",
      "pragPlay",
      "omTv",
      "docuBay",
      "stage",
      "playFlix",
      "powerKids",
      "rajTv",
      "primeFilx",
      "iStream",
      "aaoNxt",
      "iTap",
      "chaupal",
      "vrOtt",
      "shortFundly",
      "shortsTv",
      "reelDrama",
      "sanskarTv",
      "ahaTamil",
      "shemarooTv",
      "liveTv",
    ], // Array of OTT codes for this plan
  },
  // Add more plan objects as needed
];
